# Padding과 Stride의 관계

 Convolution Layer나 Pooling Layer나 `padding`, `stride` 옵션 작동 원리 자체는 동일하다. 옵션 적용 순서는 `padding` -> `stride`이다.

 이 내용을 이해하는 데 한해, 입력은 convolution 혹은 pooling을 하기 전의 데이터(주로 이미지), 중간 출력은 stride 옵션을 적용해 convolution 혹은 pooling을 하기 전, 패딩만 적용한 데이터라고 정의한다. 출력은 padding, stride 옵션을 거쳐 convolution, pooling 연산을 모두 적용한 후의 결과라고 정의한다. 

 연산 적용 전후의 이미지 사이즈 변화는 이전의 강의에서도 보았듯, `{(N+2P-F)/stride}+1`이다.


1. Padding
    - SAME: 입력과 중간 출력의 사이즈가 같아지도록 패딩을 붙인다. 인터넷을 찾아 보면 일단 2배로 이미지를 확장한다고 되어 있는데, 정확히 말하면 공식 상에서 입력 이미지가 패딩을 거쳐 `{(N+2P-F)}+1` 중간 출력으로 갈 때, 중간 출력의 이미지와 입력 이미지의 각 변의 사이즈가 같아지도록 `P`를 찾아 적용하는 게 아닐까 싶다. (documentation, 소스코드 찾아 보고 이해할 필요가 있다.)
    - VALID: 그런 거 신경 안 쓰고, 그냥 `{(N-F)}+1` 공식에 의해 중간 출력 결과를 내 놓는다.


2. Stride

 패딩된 결과에 따라 갈 수 있는 한도 안에서 stride를 적용하며 convolution 혹은 pooling 연산을 한다. 그렇게 적용하고 맞지 않는 사이즈의 data는 drop(혹은 crop)한다.

In [20]:
import numpy as np
import sys
from tensorflow.keras.layers import Conv2D, MaxPooling2D
import tensorflow as tf

In [26]:
np.set_printoptions(threshold=sys.maxsize)

In [37]:
k_size = 4
p_size = 2
sample_data = tf.constant(np.arange(1.0, 201.0).reshape(-1, 20, 10, 1), dtype=tf.float32)

## Convolution : Padding과 Stride의 관계

In [40]:
# conv padding same
sample_conv = Conv2D(filters=1, kernel_size=(k_size, k_size), strides=1, padding='same', activation='linear')(sample_data)
sample_conv2 = Conv2D(filters=1, kernel_size=(k_size, k_size), strides=2, padding='same', activation='linear')(sample_data)
sample_conv3 = Conv2D(filters=1, kernel_size=(k_size, k_size), strides=3, padding='same', activation='linear')(sample_data)
sample_conv4 = Conv2D(filters=1, kernel_size=(k_size, k_size), strides=4, padding='same', activation='linear')(sample_data)
sample_conv5 = Conv2D(filters=1, kernel_size=(k_size, k_size), strides=5, padding='same', activation='linear')(sample_data)
sample_conv6 = Conv2D(filters=1, kernel_size=(k_size, k_size), strides=6, padding='same', activation='linear')(sample_data)
sample_conv7 = Conv2D(filters=1, kernel_size=(k_size, k_size), strides=7, padding='same', activation='linear')(sample_data)
sample_conv8 = Conv2D(filters=1, kernel_size=(k_size, k_size), strides=8, padding='same', activation='linear')(sample_data)
sample_conv9 = Conv2D(filters=1, kernel_size=(k_size, k_size), strides=9, padding='same', activation='linear')(sample_data)
sample_conv10 = Conv2D(filters=1, kernel_size=(k_size, k_size), strides=10, padding='same', activation='linear')(sample_data)
sample_conv11 = Conv2D(filters=1, kernel_size=(k_size, k_size), strides=11, padding='same', activation='linear')(sample_data)
sample_conv19 = Conv2D(filters=1, kernel_size=(k_size, k_size), strides=19, padding='same', activation='linear')(sample_data)
sample_conv20 = Conv2D(filters=1, kernel_size=(k_size, k_size), strides=20, padding='same', activation='linear')(sample_data)
print(sample_conv.shape) # 패딩이 same으로 잡히니까, 출력 이미지 사이즈가 원본과 동일하다: (20, 10)
print(sample_conv2.shape) # 동일한 출력 이미지 사이즈 (20, 10)에서 strides가 2로 적용되니까 : (10, 5)
print(sample_conv3.shape) # 동일한 출력 이미지 사이즈 (20, 10)에서 strides가 3으로 적용되니까 가능한 데까지만 나온다 : 0, 3, 6, 9, 12, 15, 18 // 0, 3, 6, 9 // (7, 4)
print(sample_conv4.shape) # 동일한 출력 이미지 사이즈 (20, 10)에서 strides가 4로 적용되니가 0, 4, 8, 12, 16 // 0, 4, 8 // (5, 3)
print(sample_conv5.shape) # (20, 10) -> strides 5 적용 -> 0, 5, 10, 15 // 0, 5 -> (4, 2)
print(sample_conv6.shape) # (20, 10) -> strides 6 적용 -> 0, 6, 12, 18 // 0, 6 -> (4, 2)
print(sample_conv7.shape) # (20, 10) -> strides 7 적용 -> 0, 7, 14 // 0, 7 -> (3, 2)
print(sample_conv8.shape)
print(sample_conv9.shape)
print(sample_conv10.shape)
print(sample_conv11.shape)
print('...')
print(sample_conv19.shape)
print(sample_conv20.shape)

(1, 20, 10, 1)
(1, 10, 5, 1)
(1, 7, 4, 1)
(1, 5, 3, 1)
(1, 4, 2, 1)
(1, 4, 2, 1)
(1, 3, 2, 1)
(1, 3, 2, 1)
(1, 3, 2, 1)
(1, 2, 1, 1)
(1, 2, 1, 1)
...
(1, 2, 1, 1)
(1, 1, 1, 1)


In [41]:
# conv padding valid
sample_conv = Conv2D(filters=1, kernel_size=(k_size, k_size), strides=1, padding='valid', activation='linear')(sample_data)
sample_conv2 = Conv2D(filters=1, kernel_size=(k_size, k_size), strides=2, padding='valid', activation='linear')(sample_data)
sample_conv3 = Conv2D(filters=1, kernel_size=(k_size, k_size), strides=3, padding='valid', activation='linear')(sample_data)
sample_conv4 = Conv2D(filters=1, kernel_size=(k_size, k_size), strides=4, padding='valid', activation='linear')(sample_data)
sample_conv5 = Conv2D(filters=1, kernel_size=(k_size, k_size), strides=5, padding='valid', activation='linear')(sample_data)
sample_conv6 = Conv2D(filters=1, kernel_size=(k_size, k_size), strides=6, padding='valid', activation='linear')(sample_data)
sample_conv7 = Conv2D(filters=1, kernel_size=(k_size, k_size), strides=7, padding='valid', activation='linear')(sample_data)
sample_conv8 = Conv2D(filters=1, kernel_size=(k_size, k_size), strides=8, padding='valid', activation='linear')(sample_data)
sample_conv9 = Conv2D(filters=1, kernel_size=(k_size, k_size), strides=9, padding='valid', activation='linear')(sample_data)
sample_conv10 = Conv2D(filters=1, kernel_size=(k_size, k_size), strides=10, padding='valid', activation='linear')(sample_data)
sample_conv11 = Conv2D(filters=1, kernel_size=(k_size, k_size), strides=11, padding='valid', activation='linear')(sample_data)
sample_conv19 = Conv2D(filters=1, kernel_size=(k_size, k_size), strides=19, padding='valid', activation='linear')(sample_data)
sample_conv20 = Conv2D(filters=1, kernel_size=(k_size, k_size), strides=20, padding='valid', activation='linear')(sample_data)
print(sample_conv.shape) # 패딩 valid -> 이미지 출력 사이즈 20-4+1/1 = 17, 10-4+1/1 = 7-> (17, 7)에서 stride 1적용 -> (17, 7)
print(sample_conv2.shape) # (17, 7) -> stride 2 -> 0, 2, 4, 6, 8, 10, 12, 14, 16, 18 // 0, 2, 4, 6 -> (9, 4)
print(sample_conv3.shape) # (17, 7) -> stride 3 -> 0, 3, 6, 9, 12, 15 // 0, 3, 6 -> (6, 3)
print(sample_conv4.shape) # 
print(sample_conv5.shape) # 4, 2)
print(sample_conv6.shape) # 4, 2)
print(sample_conv7.shape) # )
print(sample_conv8.shape)
print(sample_conv9.shape)
print(sample_conv10.shape)
print(sample_conv11.shape)
print('...')
print(sample_conv19.shape) # (17, 7) -> strides 19 적용 -> 0, 0 -> 그대로 나옴
print(sample_conv20.shape)

(1, 17, 7, 1)
(1, 9, 4, 1)
(1, 6, 3, 1)
(1, 5, 2, 1)
(1, 4, 2, 1)
(1, 3, 2, 1)
(1, 3, 1, 1)
(1, 3, 1, 1)
(1, 2, 1, 1)
(1, 2, 1, 1)
(1, 2, 1, 1)
...
(1, 1, 1, 1)
(1, 1, 1, 1)


## Pooling : 여러 조합 실험

In [45]:
#  conv padding same + conv padding same + pooling stride 1 고정
sample_conv = Conv2D(filters=1, kernel_size=(k_size, k_size), strides=1, padding='same', activation='linear')(sample_data)
sample_pool = MaxPooling2D(pool_size=(p_size, p_size), strides=1, padding='same')(sample_conv)
sample_conv2 = Conv2D(filters=1, kernel_size=(k_size, k_size), strides=2, padding='same', activation='linear')(sample_data)
sample_pool2 = MaxPooling2D(pool_size=(p_size, p_size), strides=1, padding='same')(sample_conv2)
sample_conv3 = Conv2D(filters=1, kernel_size=(k_size, k_size), strides=3, padding='same', activation='linear')(sample_data)
sample_pool3 = MaxPooling2D(pool_size=(p_size, p_size), strides=1, padding='same')(sample_conv3)
sample_conv4 = Conv2D(filters=1, kernel_size=(k_size, k_size), strides=4, padding='same', activation='linear')(sample_data)
sample_pool4 = MaxPooling2D(pool_size=(p_size, p_size), strides=1, padding='same')(sample_conv4)
sample_conv5 = Conv2D(filters=1, kernel_size=(k_size, k_size), strides=5, padding='same', activation='linear')(sample_data)
sample_pool5 = MaxPooling2D(pool_size=(p_size, p_size), strides=1, padding='same')(sample_conv5)
sample_conv6 = Conv2D(filters=1, kernel_size=(k_size, k_size), strides=6, padding='same', activation='linear')(sample_data)
sample_pool6 = MaxPooling2D(pool_size=(p_size, p_size), strides=1, padding='same')(sample_conv6)
sample_conv7 = Conv2D(filters=1, kernel_size=(k_size, k_size), strides=7, padding='same', activation='linear')(sample_data)
sample_pool7 = MaxPooling2D(pool_size=(p_size, p_size), strides=1, padding='same')(sample_conv7)
sample_conv8 = Conv2D(filters=1, kernel_size=(k_size, k_size), strides=8, padding='same', activation='linear')(sample_data)
sample_pool8 = MaxPooling2D(pool_size=(p_size, p_size), strides=1, padding='same')(sample_conv8)
sample_conv9 = Conv2D(filters=1, kernel_size=(k_size, k_size), strides=9, padding='same', activation='linear')(sample_data)
sample_pool9 = MaxPooling2D(pool_size=(p_size, p_size), strides=1, padding='same')(sample_conv9)
sample_conv10 = Conv2D(filters=1, kernel_size=(k_size, k_size), strides=10, padding='same', activation='linear')(sample_data)
sample_pool10 = MaxPooling2D(pool_size=(p_size, p_size), strides=1, padding='same')(sample_conv10)
print(sample_conv.shape) 
print("      ", sample_pool.shape)
print(sample_conv2.shape)
print("      ", sample_pool2.shape)
print(sample_conv3.shape)
print("      ", sample_pool3.shape)
print(sample_conv4.shape)
print("      ", sample_pool4.shape)
print(sample_conv5.shape)
print("      ", sample_pool5.shape)
print(sample_conv6.shape)
print("      ", sample_pool6.shape)
print(sample_conv7.shape)
print("      ", sample_pool7.shape)
print(sample_conv8.shape)
print("      ", sample_pool8.shape)
print(sample_conv9.shape)
print("      ", sample_pool9.shape)
print(sample_conv10.shape)
print("      ", sample_pool10.shape)

(1, 10, 4, 1)
       (1, 10, 4, 1)
(1, 5, 2, 1)
       (1, 5, 2, 1)
(1, 4, 2, 1)
       (1, 4, 2, 1)
(1, 3, 1, 1)
       (1, 3, 1, 1)
(1, 2, 1, 1)
       (1, 2, 1, 1)
(1, 2, 1, 1)
       (1, 2, 1, 1)
(1, 2, 1, 1)
       (1, 2, 1, 1)
(1, 2, 1, 1)
       (1, 2, 1, 1)
(1, 2, 1, 1)
       (1, 2, 1, 1)
(1, 1, 1, 1)
       (1, 1, 1, 1)


In [46]:
# conv padding same + conv padding same + pooling stride 변화
sample_conv = Conv2D(filters=1, kernel_size=(k_size, k_size), strides=1, padding='same', activation='linear')(sample_data)
sample_pool = MaxPooling2D(pool_size=(p_size, p_size), strides=1, padding='same')(sample_conv)
sample_conv2 = Conv2D(filters=1, kernel_size=(k_size, k_size), strides=2, padding='same', activation='linear')(sample_data)
sample_pool2 = MaxPooling2D(pool_size=(p_size, p_size), strides=2, padding='same')(sample_conv2)
sample_conv3 = Conv2D(filters=1, kernel_size=(k_size, k_size), strides=3, padding='same', activation='linear')(sample_data)
sample_pool3 = MaxPooling2D(pool_size=(p_size, p_size), strides=3, padding='same')(sample_conv3)
sample_conv4 = Conv2D(filters=1, kernel_size=(k_size, k_size), strides=4, padding='same', activation='linear')(sample_data)
sample_pool4 = MaxPooling2D(pool_size=(p_size, p_size), strides=4, padding='same')(sample_conv4)
sample_conv5 = Conv2D(filters=1, kernel_size=(k_size, k_size), strides=5, padding='same', activation='linear')(sample_data)
sample_pool5 = MaxPooling2D(pool_size=(p_size, p_size), strides=5, padding='same')(sample_conv5)
sample_conv6 = Conv2D(filters=1, kernel_size=(k_size, k_size), strides=6, padding='same', activation='linear')(sample_data)
sample_pool6 = MaxPooling2D(pool_size=(p_size, p_size), strides=6, padding='same')(sample_conv6)
sample_conv7 = Conv2D(filters=1, kernel_size=(k_size, k_size), strides=7, padding='same', activation='linear')(sample_data)
sample_pool7 = MaxPooling2D(pool_size=(p_size, p_size), strides=7, padding='same')(sample_conv7)
sample_conv8 = Conv2D(filters=1, kernel_size=(k_size, k_size), strides=8, padding='same', activation='linear')(sample_data)
sample_pool8 = MaxPooling2D(pool_size=(p_size, p_size), strides=8, padding='same')(sample_conv8)
sample_conv9 = Conv2D(filters=1, kernel_size=(k_size, k_size), strides=9, padding='same', activation='linear')(sample_data)
sample_pool9 = MaxPooling2D(pool_size=(p_size, p_size), strides=9, padding='same')(sample_conv9)
sample_conv10 = Conv2D(filters=1, kernel_size=(k_size, k_size), strides=10, padding='same', activation='linear')(sample_data)
sample_pool10 = MaxPooling2D(pool_size=(p_size, p_size), strides=10, padding='same')(sample_conv10)
print(sample_conv.shape)
print("      ", sample_pool.shape) # 컨볼루션 결과인 (10, 4) 그대로 나온다.
print(sample_conv2.shape)
print("      ", sample_pool2.shape) # 컨볼루션 결과인 (5, 2) 유지하도록 패딩 ->  stride 2 적용할 수 있는 만큼 간다: 0, 2, 4 // 0 -> (3, 1)
print(sample_conv3.shape)
print("      ", sample_pool3.shape) # 컨볼루션 결과인 (4, 2) 유지하도록 패딩 -> stride 3 적용할 수 있는 만큼 간다: 0, 3 // 0 -> (2, 1)
print(sample_conv4.shape)
print("      ", sample_pool4.shape) # 컨볼루션 결과인 (3, 1) 유지하도록 패딩 -> stride 4 적용할 수 있는 만큼 간다: 0 // 0 -> (1, 1)
print(sample_conv5.shape)
print("      ", sample_pool5.shape)
print(sample_conv6.shape)
print("      ", sample_pool6.shape)
print(sample_conv7.shape)
print("      ", sample_pool7.shape)
print(sample_conv8.shape)
print("      ", sample_pool8.shape)
print(sample_conv9.shape)
print("      ", sample_pool9.shape)
print(sample_conv10.shape)
print("      ", sample_pool10.shape)

(1, 10, 4, 1)
       (1, 10, 4, 1)
(1, 5, 2, 1)
       (1, 3, 1, 1)
(1, 4, 2, 1)
       (1, 2, 1, 1)
(1, 3, 1, 1)
       (1, 1, 1, 1)
(1, 2, 1, 1)
       (1, 1, 1, 1)
(1, 2, 1, 1)
       (1, 1, 1, 1)
(1, 2, 1, 1)
       (1, 1, 1, 1)
(1, 2, 1, 1)
       (1, 1, 1, 1)
(1, 2, 1, 1)
       (1, 1, 1, 1)
(1, 1, 1, 1)
       (1, 1, 1, 1)


In [47]:
# conv padding same + pooling padding valid + stride 1 고정
sample_conv = Conv2D(filters=1, kernel_size=(k_size, k_size), strides=1, padding='same', activation='linear')(sample_data)
sample_pool = MaxPooling2D(pool_size=(p_size, p_size), strides=1, padding='valid')(sample_conv)
sample_conv2 = Conv2D(filters=1, kernel_size=(k_size, k_size), strides=2, padding='same', activation='linear')(sample_data)
sample_pool2 = MaxPooling2D(pool_size=(p_size, p_size), strides=1, padding='valid')(sample_conv2)
sample_conv3 = Conv2D(filters=1, kernel_size=(k_size, k_size), strides=3, padding='same', activation='linear')(sample_data)
sample_pool3 = MaxPooling2D(pool_size=(p_size, p_size), strides=1, padding='valid')(sample_conv3)
sample_conv4 = Conv2D(filters=1, kernel_size=(k_size, k_size), strides=4, padding='same', activation='linear')(sample_data)
sample_pool4 = MaxPooling2D(pool_size=(p_size, p_size), strides=1, padding='valid')(sample_conv4)
sample_conv5 = Conv2D(filters=1, kernel_size=(k_size, k_size), strides=5, padding='same', activation='linear')(sample_data)
sample_pool5 = MaxPooling2D(pool_size=(p_size, p_size), strides=1, padding='valid')(sample_conv5)
sample_conv6 = Conv2D(filters=1, kernel_size=(k_size, k_size), strides=6, padding='same', activation='linear')(sample_data)
sample_pool6 = MaxPooling2D(pool_size=(p_size, p_size), strides=1, padding='valid')(sample_conv6)
sample_conv7 = Conv2D(filters=1, kernel_size=(k_size, k_size), strides=7, padding='same', activation='linear')(sample_data)
sample_pool7 = MaxPooling2D(pool_size=(p_size, p_size), strides=1, padding='valid')(sample_conv7)
sample_conv8 = Conv2D(filters=1, kernel_size=(k_size, k_size), strides=8, padding='same', activation='linear')(sample_data)
sample_pool8 = MaxPooling2D(pool_size=(p_size, p_size), strides=1, padding='valid')(sample_conv8)
sample_conv9 = Conv2D(filters=1, kernel_size=(k_size, k_size), strides=9, padding='same', activation='linear')(sample_data)
sample_pool9 = MaxPooling2D(pool_size=(p_size, p_size), strides=1, padding='valid')(sample_conv9)
sample_conv10 = Conv2D(filters=1, kernel_size=(k_size, k_size), strides=10, padding='same', activation='linear')(sample_data)
sample_pool10 = MaxPooling2D(pool_size=(p_size, p_size), strides=1, padding='valid')(sample_conv10)
print(sample_conv.shape) 
print("      ", sample_pool.shape) # valid이므로 conv 결과가 (10-2+1)/1, (4-2+1)/1에 의해 (9, 3) -> pool stride 1이므로 (9, 3).
print(sample_conv2.shape)
print("      ", sample_pool2.shape) # conv 결과인 (5, 2)가 (5-2+1)/1, (2-2+1)/1에 의해 (4, 1) -> pool stride 1이므로 (4, 1).
print(sample_conv3.shape)
print("      ", sample_pool3.shape)
print(sample_conv4.shape)
print("      ", sample_pool4.shape) # conv 결과인 (3, 1)이 (3-2+1)/1, (1-2+1)/1에 의해 (1,0) -> 일단 중간 출력 0이 되고 나서부터는 의미가 없다!
print(sample_conv5.shape)
print("      ", sample_pool5.shape)
print(sample_conv6.shape)
print("      ", sample_pool6.shape)
print(sample_conv7.shape)
print("      ", sample_pool7.shape)
print(sample_conv8.shape)
print("      ", sample_pool8.shape)
print(sample_conv9.shape)
print("      ", sample_pool9.shape)
print(sample_conv10.shape)
print("      ", sample_pool10.shape)

(1, 10, 4, 1)
       (1, 9, 3, 1)
(1, 5, 2, 1)
       (1, 4, 1, 1)
(1, 4, 2, 1)
       (1, 3, 1, 1)
(1, 3, 1, 1)
       (1, 2, 0, 1)
(1, 2, 1, 1)
       (1, 1, 0, 1)
(1, 2, 1, 1)
       (1, 1, 0, 1)
(1, 2, 1, 1)
       (1, 1, 0, 1)
(1, 2, 1, 1)
       (1, 1, 0, 1)
(1, 2, 1, 1)
       (1, 1, 0, 1)
(1, 1, 1, 1)
       (1, 0, 0, 1)


In [49]:
# conv padding same + pooling padding valid + stride 변화
sample_conv = Conv2D(filters=1, kernel_size=(k_size, k_size), strides=1, padding='same', activation='linear')(sample_data)
sample_pool = MaxPooling2D(pool_size=(p_size, p_size), strides=1, padding='valid')(sample_conv)
sample_conv2 = Conv2D(filters=1, kernel_size=(k_size, k_size), strides=2, padding='same', activation='linear')(sample_data)
sample_pool2 = MaxPooling2D(pool_size=(p_size, p_size), strides=2, padding='valid')(sample_conv2)
sample_conv3 = Conv2D(filters=1, kernel_size=(k_size, k_size), strides=3, padding='same', activation='linear')(sample_data)
sample_pool3 = MaxPooling2D(pool_size=(p_size, p_size), strides=3, padding='valid')(sample_conv3)
sample_conv4 = Conv2D(filters=1, kernel_size=(k_size, k_size), strides=4, padding='same', activation='linear')(sample_data)
sample_pool4 = MaxPooling2D(pool_size=(p_size, p_size), strides=4, padding='valid')(sample_conv4)
sample_conv5 = Conv2D(filters=1, kernel_size=(k_size, k_size), strides=5, padding='same', activation='linear')(sample_data)
sample_pool5 = MaxPooling2D(pool_size=(p_size, p_size), strides=5, padding='valid')(sample_conv5)
sample_conv6 = Conv2D(filters=1, kernel_size=(k_size, k_size), strides=6, padding='same', activation='linear')(sample_data)
sample_pool6 = MaxPooling2D(pool_size=(p_size, p_size), strides=6, padding='valid')(sample_conv6)
sample_conv7 = Conv2D(filters=1, kernel_size=(k_size, k_size), strides=7, padding='same', activation='linear')(sample_data)
sample_pool7 = MaxPooling2D(pool_size=(p_size, p_size), strides=7, padding='valid')(sample_conv7)
sample_conv8 = Conv2D(filters=1, kernel_size=(k_size, k_size), strides=8, padding='same', activation='linear')(sample_data)
sample_pool8 = MaxPooling2D(pool_size=(p_size, p_size), strides=8, padding='valid')(sample_conv8)
sample_conv9 = Conv2D(filters=1, kernel_size=(k_size, k_size), strides=9, padding='same', activation='linear')(sample_data)
sample_pool9 = MaxPooling2D(pool_size=(p_size, p_size), strides=9, padding='valid')(sample_conv9)
sample_conv10 = Conv2D(filters=1, kernel_size=(k_size, k_size), strides=10, padding='same', activation='linear')(sample_data)
sample_pool10 = MaxPooling2D(pool_size=(p_size, p_size), strides=10, padding='valid')(sample_conv10)
print(sample_conv.shape) 
print("      ", sample_pool.shape) # valid이므로 conv 결과가 (10-2+1)/1, (4-2+1)/1에 의해 (9, 3) -> pool stride 1이므로 (9, 3).
print(sample_conv2.shape)
print("      ", sample_pool2.shape) # conv 결과인 (5, 2)가 (5-2+1)/1, (2-2+1)/1에 의해 (4, 1) -> pool stride 1이므로 (4, 1).
print(sample_conv3.shape)
print("      ", sample_pool3.shape)
print(sample_conv4.shape)
print("      ", sample_pool4.shape) # conv 결과인 (3, 1)이 (3-2+1)/1, (1-2+1)/1에 의해 (1,0) -> 일단 중간 출력 0이 되고 나서부터는 의미가 없다!
print(sample_conv5.shape)
print("      ", sample_pool5.shape)
print(sample_conv6.shape)
print("      ", sample_pool6.shape)
print(sample_conv7.shape)
print("      ", sample_pool7.shape)
print(sample_conv8.shape)
print("      ", sample_pool8.shape)
print(sample_conv9.shape)
print("      ", sample_pool9.shape)
print(sample_conv10.shape)
print("      ", sample_pool10.shape)

(1, 10, 4, 1)
       (1, 9, 3, 1)
(1, 5, 2, 1)
       (1, 2, 1, 1)
(1, 4, 2, 1)
       (1, 1, 1, 1)
(1, 3, 1, 1)
       (1, 1, 0, 1)
(1, 2, 1, 1)
       (1, 1, 0, 1)
(1, 2, 1, 1)
       (1, 1, 0, 1)
(1, 2, 1, 1)
       (1, 1, 0, 1)
(1, 2, 1, 1)
       (1, 1, 0, 1)
(1, 2, 1, 1)
       (1, 1, 0, 1)
(1, 1, 1, 1)
       (1, 0, 0, 1)


## convolution 연산 원리

In [43]:
sample_data = tf.constant(np.arange(1.0, 41.0).reshape(-1, 10, 4, 1), dtype=tf.float32)
sample_conv = Conv2D(filters=1, kernel_size=(k_size, k_size), strides=1, padding='same', activation='linear')(sample_data)
sample_pool = MaxPooling2D(pool_size=(2, 2), strides=1, padding='same')(sample_conv)

In [44]:
print(sample_data)
print(sample_conv)
print(sample_pool)

tf.Tensor(
[[[[ 1.]
   [ 2.]
   [ 3.]
   [ 4.]]

  [[ 5.]
   [ 6.]
   [ 7.]
   [ 8.]]

  [[ 9.]
   [10.]
   [11.]
   [12.]]

  [[13.]
   [14.]
   [15.]
   [16.]]

  [[17.]
   [18.]
   [19.]
   [20.]]

  [[21.]
   [22.]
   [23.]
   [24.]]

  [[25.]
   [26.]
   [27.]
   [28.]]

  [[29.]
   [30.]
   [31.]
   [32.]]

  [[33.]
   [34.]
   [35.]
   [36.]]

  [[37.]
   [38.]
   [39.]
   [40.]]]], shape=(1, 10, 4, 1), dtype=float32)
tf.Tensor(
[[[[ -3.936306  ]
   [ -2.6916444 ]
   [ -2.92038   ]
   [ -0.06611538]]

  [[ -8.436247  ]
   [ -6.5332866 ]
   [ -7.7500205 ]
   [ -0.9188719 ]]

  [[-13.340676  ]
   [-10.379387  ]
   [-12.352623  ]
   [ -1.6650438 ]]

  [[-18.245104  ]
   [-14.225485  ]
   [-16.955225  ]
   [ -2.4112148 ]]

  [[-23.149536  ]
   [-18.071587  ]
   [-21.557827  ]
   [ -3.1573877 ]]

  [[-28.053963  ]
   [-21.917686  ]
   [-26.160427  ]
   [ -3.9035587 ]]

  [[-32.958397  ]
   [-25.763784  ]
   [-30.763031  ]
   [ -4.6497297 ]]

  [[-37.862823  ]
   [-29.609886  ]
   [-3